pipeline:
  name: AudioEncoderPipeline
  stages:
    - name: Dataset
      type: DualDatasetStage
      params:
        vocl_filename: ds_vocls
        inst_filename: ds_inst
    - name: AudioToImage
      type: AudioToImageStage
      cache: 
        filename: T:/cache/AudioToImage
        seek_policy: ONE_SHOT
        max_size: 2147483648
        max_split: 50
    - name: ImageToEncoding
      type: ImageToEncodingStage
      params:
        weights: ../vgg16_weights.npz
      cache: 
        filename: T:/cache/ImageToEncoding
        seek_policy: ONE_SHOT
        max_size: 2147483648
        max_split: 50