pipeline:
  name: AudioEncoderPipeline
  remotes:
    - name: minizero
      host: minizero.local

  # profiler:
  #   host: '127.0.0.1'
  #   prefix: 'nomix_ds.'
  stages:
    - name: Dataset
      type: DualDatasetStage
      params:
        vocl_filename: /Volumes/t$/datasets/nomix_ds/ds_vocls.linux
        inst_filename: /Volumes/t$/datasets/nomix_ds/ds_vocls.linux
        base_dir: /Volumes/t$/datasets/nomix_ds
    - name: AudioToImage
      type: AudioToImageStage
      # remotes:
      #   - name: minizero
      # cache: 
      #   filename: ../cache/AudioToImage
      #   seek_policy: ONE_SHOT
      #   max_size: 2147483648
      #   max_split: 50
    - name: ImageToEncoding
      type: ImageToEncodingStage
      params:
        weights: ../vgg16_weights.npz
      # cache: 
      #   filename: ../cache/ImageToEncoding
      #   seek_policy: ONE_SHOT
      drop: true
      
        # max_size: 2147483648
        # max_split: 50